-- Insert Products
INSERT INTO products (name, brand, description, price, original_price, category, skin_type, rating, reviews_count, image_url, in_stock, stock_quantity, tags, specifications, highlights)
VALUES
  (
    'Vitamin C Brightening Serum',
    'GlowLab',
    'A powerful antioxidant serum that brightens skin tone and reduces dark spots. Our advanced formula combines 20% pure L-Ascorbic Acid with Vitamin E and Ferulic Acid.',
    45.99,
    59.99,
    'Serums',
    ARRAY['All', 'Dull', 'Aging'],
    4.8,
    324,
    '/vitamin-c-serum.jpg',
    true,
    156,
    ARRAY['Bestseller', 'Free Home Return', 'Gold List'],
    '{"size": "30ml", "texture": "Lightweight serum", "scent": "Unscented"}',
    ARRAY['20% Pure Vitamin C', 'Brightens skin tone', 'Boosts collagen']
  ),
  (
    'Hyaluronic Acid Moisturizer',
    'HydraGlow',
    'Deep hydration cream with hyaluronic acid for plump, dewy skin.',
    38.50,
    null,
    'Moisturizers',
    ARRAY['Dry', 'Normal', 'Combination'],
    4.9,
    512,
    '/moisturizer-jar.jpg',
    true,
    89,
    ARRAY['Top Rated', 'Home Replacement Service'],
    '{"size": "50g", "texture": "Rich cream", "scent": "Fragrance-free"}',
    ARRAY['Triple molecular weight HA', 'Locks in moisture', 'Plumps fine lines']
  ),
  (
    'Retinol Night Cream',
    'YouthRevive',
    'Anti-aging night cream with retinol to reduce fine lines and wrinkles.',
    52.00,
    null,
    'Treatments',
    ARRAY['Aging', 'Normal', 'Dry'],
    4.7,
    289,
    '/retinol-cream-jar.jpg',
    true,
    234,
    ARRAY['Gold List'],
    '{"size": "50ml", "texture": "Rich night cream", "scent": "Light herbal"}',
    ARRAY['0.5% Encapsulated Retinol', 'Reduces fine lines', 'Improves texture']
  ),
  (
    'Gentle Foaming Cleanser',
    'PureClean',
    'pH-balanced cleanser that removes impurities without stripping skin.',
    24.99,
    null,
    'Cleansers',
    ARRAY['All', 'Sensitive'],
    4.6,
    445,
    '/facial-cleanser-bottle.jpg',
    true,
    100,
    ARRAY['Free Home Return'],
    '{"size": "150ml", "texture": "Foam", "scent": "Fresh"}',
    ARRAY['pH-balanced', 'Gentle formula', 'Non-stripping']
  ),
  (
    'SPF 50 Sunscreen',
    'SunShield',
    'Broad-spectrum protection with lightweight, non-greasy formula.',
    28.50,
    null,
    'Sunscreen',
    ARRAY['All'],
    4.9,
    621,
    '/sunscreen-bottle.jpg',
    true,
    200,
    ARRAY['Essential', 'Gold List'],
    '{"size": "50ml", "texture": "Lightweight lotion", "scent": "Unscented"}',
    ARRAY['Broad-spectrum SPF 50', 'Non-greasy', 'No white cast']
  )
ON CONFLICT DO NOTHING;
