-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Clear existing data (optional, be careful in production)
-- TRUNCATE TABLE courses, products CASCADE;

-- Insert Products
INSERT INTO products (
  id,
  name,
  brand,
  description,
  detailed_description,
  price,
  original_price,
  category,
  skin_types,
  rating,
  review_count,
  in_stock,
  stock_quantity,
  image_url,
  badge,
  tags,
  seller,
  shipping_info,
  highlights,
  specifications
) VALUES 
(
  'd290f1ee-6c54-4b01-90e6-d701748f0851',
  'Hydra-Glow Vitamin C Serum',
  'Lumina Skin',
  'A powerful brightening serum that evens skin tone and boosts radiance.',
  'Our Hydra-Glow Vitamin C Serum is formulated with 15% L-Ascorbic Acid, Ferulic Acid, and Vitamin E to provide superior antioxidant protection. This lightweight, fast-absorbing serum helps to diminish the appearance of fine lines, wrinkles, and dark spots while instantly brightening the complexion.',
  45.00,
  58.00,
  'Serums',
  ARRAY['All', 'Dull', 'Aging'],
  4.8,
  124,
  true,
  50,
  '/placeholder.svg?height=400&width=400',
  'Best Seller',
  ARRAY['Brightening', 'Anti-aging', 'Vegan'],
  'Lumina Official',
  'Free shipping on orders over $50',
  ARRAY['Brightens skin tone', 'Reduces dark spots', 'Boosts collagen production'],
  '{"Volume": "30ml", "Scent": "Citrus", "Texture": "Lightweight liquid"}'::jsonb
),
(
  'd290f1ee-6c54-4b01-90e6-d701748f0852',
  'Calming Centella Gel Moisturizer',
  'Pure & Gentle',
  'Lightweight gel moisturizer that soothes irritated skin and provides deep hydration.',
  'Formulated with 70% Centella Asiatica extract, this gel moisturizer instantly cools and calms sensitive, red, or irritated skin. The oil-free formula absorbs quickly without leaving a sticky residue, making it perfect for oily and acne-prone skin types.',
  28.00,
  35.00,
  'Moisturizers',
  ARRAY['Oily', 'Sensitive', 'Acne-Prone'],
  4.6,
  89,
  true,
  100,
  '/placeholder.svg?height=400&width=400',
  'New Arrival',
  ARRAY['Soothing', 'Oil-free', 'Fragrance-free'],
  'Pure & Gentle Official',
  'Standard shipping 3-5 days',
  ARRAY['Soothes redness', 'Oil-free hydration', 'Strengthens skin barrier'],
  '{"Volume": "50ml", "Scent": "Unscented", "Texture": "Gel"}'::jsonb
),
(
  'd290f1ee-6c54-4b01-90e6-d701748f0853',
  'Deep Pore Cleansing Foam',
  'ClearSkin',
  'A gentle yet effective foam cleanser that removes impurities and unclogs pores.',
  'This rich, creamy foam cleanser deeply cleanses pores to remove dirt, oil, and makeup without stripping the skin of its natural moisture. Infused with Salicylic Acid and Tea Tree Oil, it helps to prevent breakouts and keep skin clear.',
  18.00,
  null,
  'Cleansers',
  ARRAY['Oily', 'Combination', 'Acne-Prone'],
  4.5,
  210,
  true,
  75,
  '/placeholder.svg?height=400&width=400',
  null,
  ARRAY['Deep cleansing', 'Acne-fighting'],
  'ClearSkin Official',
  'Standard shipping 3-5 days',
  ARRAY['Unclogs pores', 'Removes makeup', 'Controls oil'],
  '{"Volume": "150ml", "Scent": "Tea Tree", "Texture": "Cream to Foam"}'::jsonb
),
(
  'd290f1ee-6c54-4b01-90e6-d701748f0854',
  'Ultimate Sun Protection SPF 50+',
  'SunGuard',
  'Broad-spectrum sunscreen that protects against UVA and UVB rays without a white cast.',
  'Our Ultimate Sun Protection SPF 50+ offers high-level protection against sun damage. The non-greasy, lightweight formula blends seamlessly into all skin tones and leaves a natural, matte finish. Enriched with Hyaluronic Acid to keep skin hydrated throughout the day.',
  32.00,
  null,
  'Sunscreen',
  ARRAY['All', 'Sensitive'],
  4.9,
  340,
  true,
  200,
  '/placeholder.svg?height=400&width=400',
  'Top Rated',
  ARRAY['SPF 50+', 'No white cast', 'Hydrating'],
  'SunGuard Official',
  'Free shipping on orders over $50',
  ARRAY['Broad-spectrum protection', 'No white cast', 'Non-greasy'],
  '{"Volume": "50ml", "Scent": "Unscented", "Texture": "Lotion"}'::jsonb
);

-- Insert Courses
INSERT INTO courses (
  id,
  title,
  description,
  instructor_name,
  instructor_title,
  instructor_avatar,
  category,
  level,
  duration,
  price,
  original_price,
  rating,
  student_count,
  image_url,
  what_you_learn,
  requirements,
  recommended_products
) VALUES 
(
  'c390f1ee-6c54-4b01-90e6-d701748f0951',
  'Mastering the 10-Step Korean Skincare Routine',
  'Learn the secrets behind the famous 10-step routine and how to customize it for your skin type.',
  'Dr. Ji-Min Park',
  'Dermatologist',
  '/placeholder.svg?height=100&width=100',
  'Skincare Basics',
  'Beginner',
  '2h 30m',
  49.00,
  99.00,
  4.9,
  1540,
  '/placeholder.svg?height=720&width=1280',
  ARRAY['Understanding your skin type', 'Layering products correctly', 'Choosing the right ingredients'],
  ARRAY['Basic interest in skincare', 'No prior knowledge required'],
  ARRAY['d290f1ee-6c54-4b01-90e6-d701748f0851', 'd290f1ee-6c54-4b01-90e6-d701748f0853']
),
(
  'c390f1ee-6c54-4b01-90e6-d701748f0952',
  'Advanced Anti-Aging Techniques',
  'Discover professional techniques to maintain youthful skin and prevent premature aging.',
  'Sarah Jenkins',
  'Esthetician',
  '/placeholder.svg?height=100&width=100',
  'Anti-Aging',
  'Intermediate',
  '3h 15m',
  79.00,
  129.00,
  4.7,
  890,
  '/placeholder.svg?height=720&width=1280',
  ARRAY['Facial massage techniques', 'Retinoids and acids explained', 'Lifestyle factors for aging'],
  ARRAY['Basic skincare knowledge', 'Consistency in routine'],
  ARRAY['d290f1ee-6c54-4b01-90e6-d701748f0851', 'd290f1ee-6c54-4b01-90e6-d701748f0854']
),
(
  'c390f1ee-6c54-4b01-90e6-d701748f0953',
  'Acne Bootcamp: Clear Skin in 30 Days',
  'A comprehensive guide to understanding and treating acne from the inside out.',
  'Dr. Michael Chen',
  'Dermatologist',
  '/placeholder.svg?height=100&width=100',
  'Acne Treatment',
  'All Levels',
  '4h 00m',
  59.00,
  null,
  4.8,
  2100,
  '/placeholder.svg?height=720&width=1280',
  ARRAY['Identifying acne triggers', 'Diet and skin connection', 'Building an acne-safe routine'],
  ARRAY['Struggling with acne', 'Willingness to change habits'],
  ARRAY['d290f1ee-6c54-4b01-90e6-d701748f0852', 'd290f1ee-6c54-4b01-90e6-d701748f0853']
);

-- Insert Lessons for Course 1
INSERT INTO lessons (
  id,
  course_id,
  title,
  duration,
  type,
  content,
  order_index,
  video_url
) VALUES
(
  uuid_generate_v4(),
  'c390f1ee-6c54-4b01-90e6-d701748f0951',
  'Introduction to K-Beauty',
  '10:00',
  'video',
  'Overview of the course and what to expect.',
  1,
  'https://example.com/video1.mp4'
),
(
  uuid_generate_v4(),
  'c390f1ee-6c54-4b01-90e6-d701748f0951',
  'The Double Cleanse Method',
  '15:30',
  'video',
  'Why double cleansing is crucial and how to do it.',
  2,
  'https://example.com/video2.mp4'
),
(
  uuid_generate_v4(),
  'c390f1ee-6c54-4b01-90e6-d701748f0951',
  'Toners and Essences',
  '12:45',
  'video',
  'Understanding the difference between toners and essences.',
  3,
  'https://example.com/video3.mp4'
);
