DEMO_CONTENT_ITEMS = [
    {
        "kind": "product",
        "slug": "vitamin-c-serum",
        "title": "Vitamin C Brightening Serum",
        "payload": {
            "id": "vitamin-c-serum",
            "name": "Vitamin C Brightening Serum",
            "brand": "Keyan Lab",
            "category": "serum",
            "skinTypes": ["Normal", "Combination", "Oily"],
            "concerns": ["Uneven Tone", "Dark Spots", "Dullness"],
            "price": 34.99,
            "rating": 4.8,
            "image": "/vitamin-c-serum.jpg",
            "ingredients": ["Vitamin C", "Ferulic Acid", "Hyaluronic Acid"],
            "benefits": ["Brightens tone", "Supports collagen", "Adds antioxidant protection"],
        },
    },
    {
        "kind": "product",
        "slug": "ceramide-barrier-cream",
        "title": "Ceramide Barrier Cream",
        "payload": {
            "id": "ceramide-barrier-cream",
            "name": "Ceramide Barrier Cream",
            "brand": "Keyan Lab",
            "category": "moisturizer",
            "skinTypes": ["Dry", "Sensitive", "Normal"],
            "concerns": ["Dehydration", "Redness", "Barrier Damage"],
            "price": 29.99,
            "rating": 4.7,
            "image": "/ceramide-cream.jpg",
            "ingredients": ["Ceramides", "Squalane", "Panthenol"],
            "benefits": ["Repairs barrier", "Reduces water loss", "Calms sensitivity"],
        },
    },
    {
        "kind": "course",
        "slug": "skincare-fundamentals",
        "title": "Skincare Fundamentals",
        "payload": {
            "id": "skincare-fundamentals",
            "title": "Skincare Fundamentals",
            "level": "Beginner",
            "duration": "4 hours",
            "image": "/skincare-basics-course.jpg",
            "instructor": "Dr. Sarah Chen",
            "lessons": [
                {"title": "Understanding Skin Types", "duration": "15 min"},
                {"title": "Building a Routine", "duration": "20 min"},
                {"title": "Choosing Actives Safely", "duration": "18 min"},
            ],
        },
    },
    {
        "kind": "course",
        "slug": "ingredient-science",
        "title": "Ingredient Science Lab",
        "payload": {
            "id": "ingredient-science",
            "title": "Ingredient Science Lab",
            "level": "Intermediate",
            "duration": "3 hours",
            "image": "/skincare-ingredients-course.jpg",
            "instructor": "Dr. Ava Lin",
            "lessons": [
                {"title": "Humectants and Occlusives", "duration": "16 min"},
                {"title": "Retinoids and Exfoliants", "duration": "22 min"},
                {"title": "Ingredient Interactions", "duration": "20 min"},
            ],
        },
    },
    {
        "kind": "beauty_service",
        "slug": "hydrafacial-deluxe",
        "title": "HydraFacial Deluxe",
        "payload": {
            "id": "hydrafacial-deluxe",
            "name": "HydraFacial Deluxe",
            "category": "facial",
            "price": 299,
            "duration": "60 min",
            "rating": 4.9,
            "image": "/beauty-services/hydrafacial.jpg",
            "benefits": ["Deep cleansing", "Hydrating serum infusion", "Immediate glow"],
        },
    },
    {
        "kind": "community_post",
        "slug": "morning-routine-glow",
        "title": "My Morning Routine for Glowing Skin",
        "payload": {
            "id": "morning-routine-glow",
            "author": {"name": "Sarah Chen", "role": "Skincare Expert", "avatar": "/avatars/avatar-1.jpg"},
            "category": "Routines",
            "tags": ["Vitamin C", "SPF", "Hydration"],
            "likes": 342,
            "comments": 28,
            "excerpt": "A practical morning routine built around cleanser, Vitamin C, moisturizer, and SPF.",
        },
    },
]
