export interface Review {
  id: string
  userName: string
  userAvatar: string
  rating: number
  date: string
  comment: string
  verified: boolean
}

export interface BeautyService {
  id: string
  name: string
  description: string
  detailedDescription: string
  price: number
  originalPrice?: number
  duration: string
  category: "facial" | "anti-aging" | "laser" | "body" | "spa"
  image: string
  features: string[]
  benefits: string[]
  process: string[]
  faqs: { question: string; answer: string }[]
  partnerClinic: string
  rating: number
  reviewCount: number
  reviews: Review[]
  popular?: boolean
  new?: boolean
}

export const beautyServices: BeautyService[] = [
  // Facial Treatments
  {
    id: "1",
    name: "HydraFacial Deluxe",
    description:
      "Deep cleansing, exfoliation, and hydration treatment that removes impurities while nourishing your skin with intensive serums.",
    detailedDescription:
      "The HydraFacial Deluxe is a revolutionary multi-step treatment that combines cleansing, exfoliation, extraction, hydration, and antioxidant protection. Using patented Vortex-Fusion technology, this treatment deeply cleanses and removes impurities while simultaneously delivering moisturizing serums into the skin. The result is immediate, visible improvement in skin texture, tone, and appearance with no downtime. Perfect for all skin types, this treatment addresses fine lines, wrinkles, enlarged pores, oily and congested skin, and hyperpigmentation.",
    price: 299,
    originalPrice: 399,
    duration: "60 min",
    category: "facial",
    image: "/beauty-services/hydrafacial.jpg",
    features: [
      "Deep pore cleansing",
      "Exfoliation & extraction",
      "Hydrating serum infusion",
      "LED light therapy",
      "Immediate visible results",
    ],
    benefits: [
      "Instantly plumper, more radiant skin",
      "Reduced appearance of fine lines and wrinkles",
      "Improved skin texture and tone",
      "Deeply hydrated and nourished skin",
      "Clearer, more refined pores",
      "No downtime or irritation",
    ],
    process: [
      "Cleanse & Peel: Gentle exfoliation and resurfacing to uncover a new layer of skin",
      "Extract & Hydrate: Painless suction removes debris from pores while nourishing with intense moisturizers",
      "Fuse & Protect: Saturate skin with antioxidants and peptides to maximize glow",
      "LED Light Therapy: Red and blue light therapy to reduce inflammation and kill bacteria",
    ],
    faqs: [
      {
        question: "How often should I get a HydraFacial?",
        answer:
          "For optimal results, we recommend monthly treatments. However, you can safely have a HydraFacial as often as weekly.",
      },
      {
        question: "Is there any downtime?",
        answer:
          "No! HydraFacial is a gentle, non-invasive treatment with no downtime. You can return to your normal activities immediately.",
      },
      {
        question: "Is it suitable for sensitive skin?",
        answer:
          "Yes, HydraFacial is suitable for all skin types, including sensitive skin. The treatment can be customized to your specific needs.",
      },
    ],
    partnerClinic: "Glow Medical Spa",
    rating: 4.9,
    reviewCount: 234,
    reviews: [
      {
        id: "1",
        userName: "Sarah Johnson",
        userAvatar: "/avatars/avatar-1.jpg",
        rating: 5,
        date: "2024-01-15",
        comment:
          "Absolutely amazing! My skin has never looked better. The staff was professional and the results were immediate. I'm booking my next appointment already!",
        verified: true,
      },
      {
        id: "2",
        userName: "Emily Chen",
        userAvatar: "/avatars/avatar-2.jpg",
        rating: 5,
        date: "2024-01-10",
        comment: "Best facial I've ever had! My pores are so much smaller and my skin is glowing. Worth every penny!",
        verified: true,
      },
      {
        id: "3",
        userName: "Michael Brown",
        userAvatar: "/avatars/avatar-3.jpg",
        rating: 4,
        date: "2024-01-05",
        comment: "Great treatment! Very relaxing and my skin feels so smooth. Only wish it lasted a bit longer.",
        verified: true,
      },
    ],
    popular: true,
  },
  {
    id: "2",
    name: "Microdermabrasion Treatment",
    description:
      "Non-invasive exfoliation treatment that removes dead skin cells and stimulates collagen production for smoother, brighter skin.",
    detailedDescription: "",
    price: 189,
    duration: "45 min",
    category: "facial",
    image: "/beauty-services/microdermabrasion.jpg",
    features: [
      "Diamond-tip exfoliation",
      "Reduces fine lines",
      "Improves skin texture",
      "Minimizes pores",
      "Brightens complexion",
    ],
    benefits: [],
    process: [],
    faqs: [],
    partnerClinic: "Radiance Skin Clinic",
    rating: 4.7,
    reviewCount: 156,
    reviews: [],
  },
  {
    id: "3",
    name: "Chemical Peel Package",
    description:
      "Professional-grade chemical peel that targets acne, hyperpigmentation, and signs of aging for renewed, radiant skin.",
    detailedDescription: "",
    price: 249,
    duration: "50 min",
    category: "facial",
    image: "/beauty-services/chemical-peel.jpg",
    features: [
      "Customized peel strength",
      "Treats acne & scars",
      "Reduces hyperpigmentation",
      "Anti-aging benefits",
      "Post-treatment care kit",
    ],
    benefits: [],
    process: [],
    faqs: [],
    partnerClinic: "Elite Dermatology Center",
    rating: 4.8,
    reviewCount: 189,
    reviews: [],
  },
  {
    id: "4",
    name: "Oxygen Facial",
    description:
      "Luxurious treatment that infuses oxygen and vitamins into the skin for instant hydration and a radiant glow.",
    detailedDescription: "",
    price: 219,
    duration: "55 min",
    category: "facial",
    image: "/beauty-services/oxygen-facial.jpg",
    features: [
      "Oxygen infusion therapy",
      "Vitamin & mineral boost",
      "Instant radiance",
      "Plumps fine lines",
      "Red carpet ready",
    ],
    benefits: [],
    process: [],
    faqs: [],
    partnerClinic: "Luxe Beauty Studio",
    rating: 4.6,
    reviewCount: 98,
    reviews: [],
    new: true,
  },

  // Anti-Aging Treatments
  {
    id: "5",
    name: "Botox & Fillers Combo",
    description:
      "Comprehensive anti-aging treatment combining Botox for wrinkle reduction and dermal fillers for volume restoration.",
    detailedDescription: "",
    price: 899,
    originalPrice: 1199,
    duration: "90 min",
    category: "anti-aging",
    image: "/beauty-services/botox-fillers.jpg",
    features: [
      "Wrinkle reduction",
      "Volume restoration",
      "Natural-looking results",
      "FDA-approved products",
      "Expert injector",
    ],
    benefits: [],
    process: [],
    faqs: [],
    partnerClinic: "Premier Aesthetics Clinic",
    rating: 4.9,
    reviewCount: 312,
    reviews: [],
    popular: true,
  },
  {
    id: "6",
    name: "RF Skin Tightening",
    description:
      "Non-surgical radiofrequency treatment that tightens skin, reduces wrinkles, and stimulates collagen production.",
    detailedDescription: "",
    price: 599,
    duration: "75 min",
    category: "anti-aging",
    image: "/beauty-services/rf-tightening.jpg",
    features: [
      "Non-invasive lifting",
      "Collagen stimulation",
      "Tightens sagging skin",
      "No downtime",
      "Long-lasting results",
    ],
    benefits: [],
    process: [],
    faqs: [],
    partnerClinic: "Youth Restore Clinic",
    rating: 4.7,
    reviewCount: 145,
    reviews: [],
  },
  {
    id: "7",
    name: "Microneedling with PRP",
    description:
      "Advanced collagen induction therapy combined with platelet-rich plasma for maximum skin rejuvenation and healing.",
    detailedDescription: "",
    price: 699,
    duration: "90 min",
    category: "anti-aging",
    image: "/beauty-services/microneedling-prp.jpg",
    features: [
      "Collagen induction",
      "PRP growth factors",
      "Reduces scars & wrinkles",
      "Improves skin texture",
      "Natural regeneration",
    ],
    benefits: [],
    process: [],
    faqs: [],
    partnerClinic: "Regenerate Medical Spa",
    rating: 4.8,
    reviewCount: 201,
    reviews: [],
  },
  {
    id: "8",
    name: "Thread Lift",
    description:
      "Minimally invasive facelift alternative using dissolvable threads to lift and tighten sagging facial skin.",
    detailedDescription: "",
    price: 1299,
    duration: "120 min",
    category: "anti-aging",
    image: "/beauty-services/thread-lift.jpg",
    features: [
      "Instant lifting effect",
      "Stimulates collagen",
      "Minimal downtime",
      "Natural-looking results",
      "Lasts 12-18 months",
    ],
    benefits: [],
    process: [],
    faqs: [],
    partnerClinic: "Sculpt & Lift Clinic",
    rating: 4.9,
    reviewCount: 87,
    reviews: [],
    new: true,
  },

  // Laser Treatments
  {
    id: "9",
    name: "Laser Hair Removal - Full Body",
    description:
      "Complete full-body laser hair removal package for smooth, hair-free skin using advanced diode laser technology.",
    detailedDescription: "",
    price: 2499,
    originalPrice: 3499,
    duration: "180 min",
    category: "laser",
    image: "/beauty-services/laser-hair-removal.jpg",
    features: [
      "Full body coverage",
      "6-session package",
      "Painless technology",
      "All skin types",
      "Permanent reduction",
    ],
    benefits: [],
    process: [],
    faqs: [],
    partnerClinic: "Smooth Skin Laser Center",
    rating: 4.8,
    reviewCount: 267,
    reviews: [],
    popular: true,
  },
  {
    id: "10",
    name: "Laser Skin Resurfacing",
    description:
      "Fractional CO2 laser treatment that resurfaces skin, reduces wrinkles, and improves texture and tone.",
    detailedDescription: "",
    price: 899,
    duration: "60 min",
    category: "laser",
    image: "/beauty-services/laser-resurfacing.jpg",
    features: ["Fractional CO2 laser", "Reduces wrinkles", "Improves texture", "Treats acne scars", "Dramatic results"],
    benefits: [],
    process: [],
    faqs: [],
    partnerClinic: "Laser Skin Institute",
    rating: 4.7,
    reviewCount: 134,
    reviews: [],
  },
  {
    id: "11",
    name: "Pigmentation Removal",
    description: "Targeted laser treatment to remove age spots, sun damage, and hyperpigmentation for even-toned skin.",
    detailedDescription: "",
    price: 449,
    duration: "45 min",
    category: "laser",
    image: "/beauty-services/pigmentation-removal.jpg",
    features: ["Targets dark spots", "Removes sun damage", "Even skin tone", "Safe & effective", "Minimal downtime"],
    benefits: [],
    process: [],
    faqs: [],
    partnerClinic: "Clear Skin Laser Clinic",
    rating: 4.6,
    reviewCount: 178,
    reviews: [],
  },
  {
    id: "12",
    name: "Vascular Lesion Treatment",
    description:
      "Laser treatment for spider veins, broken capillaries, and redness using advanced vascular laser technology.",
    detailedDescription: "",
    price: 399,
    duration: "40 min",
    category: "laser",
    image: "/beauty-services/vascular-treatment.jpg",
    features: ["Removes spider veins", "Reduces redness", "Treats rosacea", "Quick treatment", "Visible improvement"],
    benefits: [],
    process: [],
    faqs: [],
    partnerClinic: "Vein & Vascular Center",
    rating: 4.5,
    reviewCount: 92,
    reviews: [],
  },

  // Body Treatments
  {
    id: "13",
    name: "Body Contouring Package",
    description:
      "Non-surgical body sculpting treatment using cryolipolysis to freeze and eliminate stubborn fat cells.",
    detailedDescription: "",
    price: 1499,
    duration: "120 min",
    category: "body",
    image: "/beauty-services/body-contouring.jpg",
    features: [
      "Freezes fat cells",
      "Targets stubborn areas",
      "No surgery required",
      "Natural elimination",
      "3-area treatment",
    ],
    benefits: [],
    process: [],
    faqs: [],
    partnerClinic: "Sculpt Body Studio",
    rating: 4.7,
    reviewCount: 156,
    reviews: [],
    popular: true,
  },
  {
    id: "14",
    name: "Cellulite Reduction",
    description: "Advanced acoustic wave therapy combined with massage to reduce cellulite and improve skin texture.",
    detailedDescription: "",
    price: 599,
    duration: "60 min",
    category: "body",
    image: "/beauty-services/cellulite-reduction.jpg",
    features: [
      "Acoustic wave therapy",
      "Reduces cellulite",
      "Improves circulation",
      "Smooths skin texture",
      "6-session package",
    ],
    benefits: [],
    process: [],
    faqs: [],
    partnerClinic: "Body Beautiful Spa",
    rating: 4.4,
    reviewCount: 89,
    reviews: [],
  },
  {
    id: "15",
    name: "Slimming Treatment",
    description: "Comprehensive body slimming package combining RF, cavitation, and lymphatic drainage for inch loss.",
    detailedDescription: "",
    price: 799,
    duration: "90 min",
    category: "body",
    image: "/beauty-services/slimming-treatment.jpg",
    features: [
      "RF fat reduction",
      "Ultrasonic cavitation",
      "Lymphatic drainage",
      "Inch loss guarantee",
      "4-session package",
    ],
    benefits: [],
    process: [],
    faqs: [],
    partnerClinic: "Slim & Tone Center",
    rating: 4.6,
    reviewCount: 123,
    reviews: [],
  },
  {
    id: "16",
    name: "Luxury Body Scrub & Wrap",
    description: "Indulgent spa treatment featuring full-body exfoliation and nourishing wrap for silky smooth skin.",
    detailedDescription: "",
    price: 289,
    duration: "90 min",
    category: "body",
    image: "/beauty-services/body-wrap.jpg",
    features: ["Full body exfoliation", "Detoxifying wrap", "Deep hydration", "Relaxing massage", "Silky smooth skin"],
    benefits: [],
    process: [],
    faqs: [],
    partnerClinic: "Serenity Spa & Wellness",
    rating: 4.8,
    reviewCount: 167,
    reviews: [],
  },

  // Spa Packages
  {
    id: "17",
    name: "Luxury Spa Day",
    description: "Ultimate relaxation package including facial, massage, body treatment, and access to spa facilities.",
    detailedDescription: "",
    price: 599,
    originalPrice: 799,
    duration: "240 min",
    category: "spa",
    image: "/beauty-services/luxury-spa-day.jpg",
    features: [
      "Signature facial",
      "Full body massage",
      "Body scrub & wrap",
      "Spa facility access",
      "Refreshments included",
    ],
    benefits: [],
    process: [],
    faqs: [],
    partnerClinic: "Tranquility Day Spa",
    rating: 4.9,
    reviewCount: 289,
    reviews: [],
    popular: true,
  },
  {
    id: "18",
    name: "Detox Package",
    description: "Comprehensive detoxification treatment combining infrared sauna, lymphatic drainage, and detox wrap.",
    detailedDescription: "",
    price: 399,
    duration: "150 min",
    category: "spa",
    image: "/beauty-services/detox-package.jpg",
    features: [
      "Infrared sauna session",
      "Lymphatic drainage massage",
      "Detoxifying body wrap",
      "Herbal tea & consultation",
      "Cleansing benefits",
    ],
    benefits: [],
    process: [],
    faqs: [],
    partnerClinic: "Pure Wellness Spa",
    rating: 4.7,
    reviewCount: 145,
    reviews: [],
  },
  {
    id: "19",
    name: "Bridal Beauty Package",
    description: "Complete pre-wedding beauty preparation including facial, body treatments, and makeup trial.",
    detailedDescription: "",
    price: 1299,
    duration: "300 min",
    category: "spa",
    image: "/beauty-services/bridal-package.jpg",
    features: [
      "Bridal facial",
      "Body polish & wrap",
      "Manicure & pedicure",
      "Makeup trial",
      "Hair styling consultation",
    ],
    benefits: [],
    process: [],
    faqs: [],
    partnerClinic: "Bridal Glow Studio",
    rating: 4.9,
    reviewCount: 198,
    reviews: [],
    new: true,
  },
  {
    id: "20",
    name: "Monthly Membership",
    description:
      "Unlimited access to select treatments, spa facilities, and exclusive member benefits with monthly subscription.",
    detailedDescription: "",
    price: 299,
    duration: "Monthly",
    category: "spa",
    image: "/beauty-services/membership.jpg",
    features: [
      "2 treatments per month",
      "Unlimited spa access",
      "20% off all services",
      "Priority booking",
      "Member-only events",
    ],
    benefits: [],
    process: [],
    faqs: [],
    partnerClinic: "Elite Wellness Club",
    rating: 4.8,
    reviewCount: 412,
    reviews: [],
  },
]

export const categories = [
  { id: "all", name: "All Services", count: 20 },
  { id: "facial", name: "Facial Treatments", count: 4 },
  { id: "anti-aging", name: "Anti-Aging", count: 4 },
  { id: "laser", name: "Laser Treatments", count: 4 },
  { id: "body", name: "Body Treatments", count: 4 },
  { id: "spa", name: "Spa Packages", count: 4 },
]
