export const MOCK_COURSES = [
  {
    id: "c1",
    title: "Advanced Skincare Fundamentals",
    description:
      "Learn the science behind skincare ingredients and how to build effective routines for different skin types.",
    instructor_name: "Dr. Sarah Chen",
    category: "Skincare Science",
    level: "Intermediate",
    duration: "4h 30m",
    price: 49.99,
    original_price: 99.99,
    rating: 4.8,
    students_count: 1250,
    thumbnail: "/skincare-science.jpg",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    curriculum: [
      "Introduction to Skin Anatomy",
      "Understanding pH Levels",
      "Active Ingredients Deep Dive",
      "Building a Routine",
      "Treating Acne and Hyperpigmentation",
    ],
  },
  {
    id: "c2",
    title: "Facial Massage Mastery",
    description:
      "Master professional facial massage techniques to improve circulation, reduce puffiness, and enhance product absorption.",
    instructor_name: "Elena Rodriguez",
    category: "Techniques",
    level: "Beginner",
    duration: "2h 15m",
    price: 29.99,
    original_price: 59.99,
    rating: 4.9,
    students_count: 850,
    thumbnail: "/facial-massage.png",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    curriculum: [
      "Benefits of Facial Massage",
      "Lymphatic Drainage Basics",
      "Gua Sha Techniques",
      "Anti-Aging Massage",
      "Daily 5-Minute Routine",
    ],
  },
  {
    id: "c3",
    title: "Korean Skincare Secrets",
    description:
      "Discover the 10-step Korean skincare routine and the philosophy behind K-Beauty for glowing, glass skin.",
    instructor_name: "Ji-Min Park",
    category: "K-Beauty",
    level: "All Levels",
    duration: "3h 45m",
    price: 39.99,
    original_price: 79.99,
    rating: 4.7,
    students_count: 2100,
    thumbnail: "/korean-skincare-products.png",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    curriculum: [
      "The K-Beauty Philosophy",
      "Double Cleansing Explained",
      "The 7-Skin Method",
      "Sheet Masks and Essences",
      "Sun Protection is Key",
    ],
  },
  {
    id: "c4",
    title: "Holistic Acne Treatment",
    description:
      "A comprehensive guide to treating acne from the inside out, covering diet, lifestyle, and gentle skincare.",
    instructor_name: "Dr. Michael Thorne",
    category: "Dermatology",
    level: "Advanced",
    duration: "5h 00m",
    price: 59.99,
    original_price: 119.99,
    rating: 4.9,
    students_count: 980,
    thumbnail: "/acne-treatment.png",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    curriculum: [
      "Types of Acne",
      "Diet and Skin Connection",
      "Stress and Hormones",
      "Skincare Ingredients to Avoid",
      "Healing Acne Scars",
    ],
  },
]

export const MOCK_PRODUCTS = [
  {
    id: "p1",
    name: "Hydrating Hyaluronic Serum",
    brand: "Lumière",
    description: "Intense hydration for plump, dewy skin. Formulated with multi-molecular weight hyaluronic acid.",
    price: 24.99,
    original_price: 35.0,
    category: "Serums",
    skin_types: ["Dry", "Normal", "Sensitive"],
    rating: 4.8,
    review_count: 342,
    in_stock: true,
    image_url: "/serum-bottle.jpg",
    badge: "Best Seller",
    highlights: ["Deeply hydrates", "Plumps fine lines", "Fragrance-free", "Vegan & Cruelty-free"],
    detailed_description:
      "Our Hydrating Hyaluronic Serum is a game-changer for dry and dehydrated skin. It penetrates deep into the skin layers to provide long-lasting moisture, leaving your skin feeling soft, supple, and rejuvenated.",
  },
  {
    id: "p2",
    name: "Vitamin C Brightening Cream",
    brand: "Lumière",
    description: "Fade dark spots and even out skin tone with our potent Vitamin C moisturizer.",
    price: 32.5,
    original_price: 45.0,
    category: "Moisturizers",
    skin_types: ["Combination", "Oily", "Normal"],
    rating: 4.6,
    review_count: 189,
    in_stock: true,
    image_url: "/vitamin-c-cream.jpg",
    badge: "New",
    highlights: ["Brightens complexion", "Antioxidant protection", "Lightweight texture", "Non-comedogenic"],
    detailed_description:
      "Wake up to brighter, more radiant skin with our Vitamin C Brightening Cream. Packed with antioxidants, it fights free radicals and helps reduce the appearance of hyperpigmentation and sun damage.",
  },
  {
    id: "p3",
    name: "Gentle Foaming Cleanser",
    brand: "PureSkin",
    description: "A pH-balanced cleanser that removes impurities without stripping the skin's natural barrier.",
    price: 18.0,
    original_price: 22.0,
    category: "Cleansers",
    skin_types: ["All Skin Types"],
    rating: 4.9,
    review_count: 520,
    in_stock: true,
    image_url: "/face-cleanser.jpg",
    badge: null,
    highlights: ["pH balanced (5.5)", "Removes makeup", "Sulfate-free", "Soothing botanicals"],
    detailed_description:
      "Cleanse your way to healthy skin with our Gentle Foaming Cleanser. It effectively removes dirt, oil, and makeup while maintaining your skin's delicate moisture balance. Perfect for daily use.",
  },
  {
    id: "p4",
    name: "Retinol Night Oil",
    brand: "AgeDefy",
    description: "Transform your skin while you sleep. Reduces wrinkles and improves skin texture.",
    price: 42.0,
    original_price: 60.0,
    category: "Treatments",
    skin_types: ["Mature", "Dry", "Combination"],
    rating: 4.7,
    review_count: 215,
    in_stock: false,
    image_url: "/retinol-oil.jpg",
    badge: "Sold Out",
    highlights: ["Anti-aging", "Improves texture", "Boosts collagen", "Nourishing oils"],
    detailed_description:
      "Experience the power of retinol without the irritation. Our Retinol Night Oil combines pure retinol with soothing plant oils to target signs of aging, revealing smoother, younger-looking skin.",
  },
  {
    id: "p5",
    name: "Purifying Clay Mask",
    brand: "PureSkin",
    description: "Detoxify your pores with this mineral-rich green clay mask. Perfect for a weekly deep cleanse.",
    price: 28.0,
    original_price: 38.0,
    category: "Masks",
    skin_types: ["Oily", "Combination", "Acne-Prone"],
    rating: 4.5,
    review_count: 156,
    in_stock: true,
    image_url: "/clay-mask.jpg",
    badge: "Trending",
    highlights: ["Deep cleansing", "Minimizes pores", "Controls oil", "Non-drying formula"],
    detailed_description:
      "Say goodbye to clogged pores. Our Purifying Clay Mask draws out impurities and excess oil without stripping your skin. Enriched with soothing botanicals to calm inflammation.",
  },
  {
    id: "p6",
    name: "Invisible Daily SPF 50",
    brand: "SunGuard",
    description: "Broad-spectrum protection that leaves no white cast. Lightweight and perfect under makeup.",
    price: 34.0,
    original_price: 40.0,
    category: "Sunscreen",
    skin_types: ["All Skin Types"],
    rating: 4.9,
    review_count: 890,
    in_stock: true,
    image_url: "/sunscreen.jpg",
    badge: "Essential",
    highlights: ["SPF 50 PA++++", "No white cast", "Reef safe", "Hydrating finish"],
    detailed_description:
      "Protect your skin from UV damage with our Invisible Daily SPF 50. This advanced formula absorbs quickly, leaving a natural finish that works beautifully as a primer for makeup.",
  },
  {
    id: "p7",
    name: "Rose Quartz Gua Sha",
    brand: "ZenTools",
    description: "Sculpt and depuff your face with this traditional beauty tool. Promotes lymphatic drainage.",
    price: 22.0,
    original_price: 30.0,
    category: "Tools",
    skin_types: ["All Skin Types"],
    rating: 4.8,
    review_count: 420,
    in_stock: true,
    image_url: "/gua-sha.jpg",
    badge: null,
    highlights: ["Genuine Rose Quartz", "Reduces puffiness", "Sculpts contours", "Relieves tension"],
    detailed_description:
      "Elevate your self-care routine with our Rose Quartz Gua Sha. Use it with your favorite facial oil to massage the face, improve circulation, and achieve a lifted, radiant look.",
  },
  {
    id: "p8",
    name: "Glow Exfoliating Toner",
    brand: "Lumière",
    description: "Gentle chemical exfoliation for smoother, brighter skin. Contains AHA and BHA.",
    price: 26.0,
    original_price: 32.0,
    category: "Toners",
    skin_types: ["Normal", "Combination", "Oily"],
    rating: 4.6,
    review_count: 275,
    in_stock: true,
    image_url: "/toner-bottle.jpg",
    badge: "Customer Pick",
    highlights: ["Exfoliates dead skin", "Unclogs pores", "Brightens tone", "Alcohol-free"],
    detailed_description:
      "Reveal your inner glow with our Glow Exfoliating Toner. A balanced blend of AHAs and BHAs gently dissolves dead skin cells and unclogs pores, leaving your complexion smooth and luminous.",
  },
  {
    id: "p9",
    name: "Peptide Repair Eye Cream",
    brand: "AgeDefy",
    description: "Target fine lines and dark circles with this peptide-packed eye cream.",
    price: 38.0,
    original_price: 55.0,
    category: "Eye Care",
    skin_types: ["All Skin Types"],
    rating: 4.7,
    review_count: 198,
    in_stock: true,
    image_url: "/eye-cream.jpg",
    badge: null,
    highlights: ["Reduces dark circles", "Smooths fine lines", "Firming peptides", "Fragrance-free"],
    detailed_description:
      "Awaken tired eyes with our Peptide Repair Eye Cream. Formulated to strengthen the delicate eye area, it reduces the appearance of crow's feet and dark circles for a refreshed look.",
  },
  {
    id: "p10",
    name: "Berry Lip Sleeping Mask",
    brand: "PureSkin",
    description: "Wake up to soft, kissable lips. Intensive overnight hydration with berry antioxidants.",
    price: 16.0,
    original_price: 20.0,
    category: "Lip Care",
    skin_types: ["All Skin Types"],
    rating: 4.9,
    review_count: 650,
    in_stock: true,
    image_url: "/lip-mask.jpg",
    badge: "Best Value",
    highlights: ["Intense hydration", "Berry extracts", "Softens lips", "Non-sticky"],
    detailed_description:
      "Rescue dry, chapped lips overnight. Our Berry Lip Sleeping Mask creates a protective moisture barrier, melting away dead skin cells to reveal smooth, plump lips by morning.",
  },
  {
    id: "p11",
    name: "Coffee Body Scrub",
    brand: "PureSkin",
    description: "Invigorating body scrub made with organic coffee grounds to exfoliate and smooth skin.",
    price: 24.0,
    original_price: 30.0,
    category: "Body Care",
    skin_types: ["All Skin Types"],
    rating: 4.7,
    review_count: 310,
    in_stock: true,
    image_url: "/body-scrub.jpg",
    badge: "New",
    highlights: ["Exfoliates", "Improves circulation", "Reduces cellulite", "Moisturizing oils"],
    detailed_description:
      "Wake up your skin with our Coffee Body Scrub. The caffeine stimulates blood flow while the grounds buff away dead skin cells, leaving your body feeling incredibly soft and energized.",
  },
  {
    id: "p12",
    name: "Niacinamide 10% Serum",
    brand: "Lumière",
    description: "A high-strength vitamin and mineral blemish formula to regulate sebum and minimize pores.",
    price: 19.99,
    original_price: 25.0,
    category: "Serums",
    skin_types: ["Oily", "Combination", "Acne-Prone"],
    rating: 4.8,
    review_count: 890,
    in_stock: true,
    image_url: "/niacinamide-serum.jpg",
    badge: "Top Rated",
    highlights: ["Regulates oil", "Minimizes pores", "Reduces redness", "Strengthens barrier"],
    detailed_description:
      "Balance your complexion with our Niacinamide 10% Serum. This powerhouse ingredient targets breakouts, minimizes the appearance of pores, and regulates oil production for clearer, healthier skin.",
  },
]
